version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_php
    container_name: laravel_php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
  
  mysql:
    image: mysql:latest
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: webshop_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

